name: New University or College
description: >
  File a request to add the blackboard instance
  of your university or college to Blackboard Sync
title: "[New University]: "
labels: ["uni-new"]
body:
  - type: markdown
    attributes:
      value: |
        **Please make sure to read UNIVERSITIES.md first**
        Thanks for taking the time to fill this request form!
        I will verify this data and add this to the project shortly.
        Please do not use this form to report a bug.
  - type: input
    id: name
    attributes:
      label: University name
      description: What is the full name of your university?
      placeholder: ex. University of Central Lancashire
    validations:
      required: true
  - type: input
    id: short-name
    attributes:
      label: University abbreviation
      description: >
        If your university has a common abbreviation, please enter it here.
      placeholder: ex. UCLan
    validations:
      required: false
  - type: dropdown
    id: country
    attributes:
      label: University country
      description: >
        Where is your university located?
      multiple: false
      options:
        - افغانستان
        - Åland
        - Shqipëria
        - الجزائر
        - American Samoa
        - Andorra
        - Angola
        - Anguilla
        - Antarctica
        - Antigua and Barbuda
        - Argentina
        - Հայաստան
        - Aruba
        - Australia
        - Österreich
        - Azərbaycan
        - Bahamas
        - ‏البحرين
        - Bangladesh
        - Barbados
        - Белару́сь
        - België
        - Belize
        - Bénin
        - Bermuda
        - ʼbrug-yul
        - Bolivia
        - Bonaire
        - Bosna i Hercegovina
        - Botswana
        - Bouvetøya
        - Brasil
        - British Indian Ocean Territory
        - British Virgin Islands
        - Negara Brunei Darussalam
        - България
        - Burkina Faso
        - Burundi
        - Kâmpŭchéa
        - Cameroon
        - Canada
        - Cabo Verde
        - Cayman Islands
        - Ködörösêse tî Bêafrîka
        - Tchad
        - Chile
        - 中国
        - Christmas Island
        - Cocos (Keeling) Islands
        - Colombia
        - Komori
        - Cook Islands
        - Costa Rica
        - Hrvatska
        - Cuba
        - Curaçao
        - Κύπρος
        - Česká republika
        - République démocratique du Congo
        - Danmark
        - Djibouti
        - Dominica
        - República Dominicana
        - Timor-Leste
        - Ecuador
        - مصر‎
        - El Salvador
        - Guinea Ecuatorial
        - ኤርትራ
        - Eesti
        - Eswatini
        - ኢትዮጵያ
        - Falkland Islands
        - Føroyar
        - Fiji
        - Suomi
        - France
        - Guyane française
        - Polynésie française
        - Territoire des Terres australes et antarctiques fr
        - Gabon
        - Gambia
        - საქართველო
        - Deutschland
        - Ghana
        - Gibraltar
        - Ελλάδα
        - Kalaallit Nunaat
        - Grenada
        - Guadeloupe
        - Guam
        - Guatemala
        - Guernsey
        - Guinée
        - Guiné-Bissau
        - Guyana
        - Haïti
        - Heard Island and McDonald Islands
        - Honduras
        - 香港
        - Magyarország
        - Ísland
        - भारत
        - Indonesia
        - ایران
        - العراق
        - Éire
        - Isle of Man
        - יִשְׂרָאֵל
        - Italia
        - Côte d'Ivoire
        - Jamaica
        - 日本
        - Jersey
        - الأردن
        - Қазақстан
        - Kenya
        - Kiribati
        - Republika e Kosovës
        - الكويت
        - Кыргызстан
        - ສປປລາວ
        - Latvija
        - لبنان
        - Lesotho
        - Liberia
        - ‏ليبيا
        - Liechtenstein
        - Lietuva
        - Luxembourg
        - 澳門
        - Madagasikara
        - Malawi
        - Malaysia
        - Maldives
        - Mali
        - Malta
        - M̧ajeļ
        - Martinique
        - موريتانيا
        - Maurice
        - Mayotte
        - México
        - Micronesia
        - Moldova
        - Monaco
        - Монгол улс
        - Црна Гора
        - Montserrat
        - المغرب
        - Moçambique
        - မြန်မာ
        - Namibia
        - Nauru
        - नेपाल
        - Nederland
        - Nouvelle-Calédonie
        - New Zealand
        - Nicaragua
        - Niger
        - Nigeria
        - Niuē
        - Norfolk Island
        - 북한
        - Северна Македонија
        - Northern Mariana Islands
        - Norge
        - عمان
        - Pakistan
        - Palau
        - فلسطين
        - Panamá
        - Papua Niugini
        - Paraguay
        - Perú
        - Pilipinas
        - Pitcairn Islands
        - Polska
        - Portugal
        - Puerto Rico
        - قطر
        - République du Congo
        - La Réunion
        - România
        - Россия
        - Rwanda
        - Saint-Barthélemy
        - Saint Helena
        - Saint Kitts and Nevis
        - Saint Lucia
        - Saint-Martin
        - Saint-Pierre-et-Miquelon
        - Saint Vincent and the Grenadines
        - Samoa
        - San Marino
        - São Tomé e Príncipe
        - العربية السعودية
        - Sénégal
        - Србија
        - Seychelles
        - Sierra Leone
        - Singapore
        - Sint Maarten
        - Slovensko
        - Slovenija
        - Solomon Islands
        - Soomaaliya
        - South Africa
        - South Georgia
        - 대한민국
        - South Sudan
        - España
        - śrī laṃkāva
        - السودان
        - Suriname
        - Svalbard og Jan Mayen
        - Sverige
        - Schweiz
        - سوريا
        - 臺灣
        - Тоҷикистон
        - Tanzania
        - ประเทศไทย
        - Togo
        - Tokelau
        - Tonga
        - Trinidad and Tobago
        - تونس
        - Türkiye
        - Türkmenistan
        - Turks and Caicos Islands
        - Tuvalu
        - United States Minor Outlying Islands
        - United States Virgin Islands
        - Uganda
        - Україна
        - دولة الإمارات العربية المتحدة
        - United Kingdom
        - United States
        - Uruguay
        - O'zbekiston
        - Vanuatu
        - Vaticano
        - Venezuela
        - Việt Nam
        - Wallis et Futuna
        - الصحراء الغربية
        - اليَمَن
        - Zambia
        - Zimbabwe
    validations:
      required: true
  - type: input
    id: login-start-url
    attributes:
      label: URL of university Blackboard instance
      description: >
        What is the URL you visit when you want to
        access Blackboard?
      placeholder: ex. https://portal.uclan.ac.uk
    validations:
      required: true
  - type: input
    id: login-target-url
    attributes:
      label: URL after logging in
      description: >
        What is the URL you are redirected to
        after successfully logging in to Blackboard?
      placeholder: ex. https://portal.uclan.ac.uk/ultra
    validations:
      required: true
  - type: input
    id: network-name
    attributes:
      label: University network name
      description: >
        Network data used for automatic university detection.

        Simply copy the network name as shown [here](
        https://74mxmsvvgqw6t23xycgaauf3cy0vyncw.lambda-url.eu-west-2.on.aws/)
        when visited from a university network.

        Please leave empty if not applicable, or you are unable to check for
        some other reason.

        Read UNIVERSITIES.md for more information.
      placeholder: UNI-CENT-LANCS
    validations:
      required: false
  - type: textarea
    id: data-sources
    attributes:
      label: Valid Blackboard data sources (optional)
      description: >
        This field is not required unless you have insider
        knowledge of the data sources used in your university.

        Read UNIVERSITIES.md for more information.
      placeholder: __00_0
    validations:
      required: false
  - type: textarea
    id: other-details
    attributes:
      label: Anything else to add?
      description: >
        If there is anything else needed to know about
        the login process for your university, you can say so here.
      placeholder: ...
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: License
      description: >
        By submitting this issue, you agree
        that your contribution may be licensed under GPL v2.
      options:
        - label: I agree to follow this project's License
          required: true
