name: New University or College
description: >
  File a request to add the blackboard instance
  of your university or college to Blackboard Sync
title: "[New University]: "
labels: ["uni-new"]
assignees:
  - sanjacob
body:
  - type: markdown
    attributes:
      value: |
        **Please make sure to read UNIVERSITIES.md first**
        Thanks for taking the time to fill this request form!
        I will verify this data and add this to the project shortly.
        Please do not use this form to report a bug.
  - type: input
    id: uni-name
    attributes:
      label: University name
      description: What is the full name of your university?
      placeholder: ex. University of Central Lancashire
    validations:
      required: true
  - type: input
    id: uni-short-name
    attributes:
      label: University abbreviation
      description: >
        If your university has a common abbreviation, please enter it here.
      placeholder: ex. UCLan
    validations:
      required: false
  - type: input
    id: login-start-url
    attributes:
      label: URL of university Blackboard instance
      description: >
        What is the URL you visit when you want to
        access Blackboard?
      placeholder: ex. https://portal.uclan.ac.uk
    validations:
      required: true
  - type: input
    id: login-target-url
    attributes:
      label: URL after logging into Blackboard instance
      description: >
        What is the URL you are redirected to
        after successfully logging in to Blackboard?
      placeholder: ex. https://portal.uclan.ac.uk/ultra
    validations:
      required: true
  - type: textarea
    id: network
    attributes:
      label: University network information
      description: >
        Network data used for automatic university detection.

        Simply copy the details shown [here](
        https://74mxmsvvgqw6t23xycgaauf3cy0vyncw.lambda-url.eu-west-2.on.aws/).

        Read UNIVERSITIES.md for more information.
      placeholder: >
        Name: UNI-CENT-LANCS

        Description: University of Central Lancashire

        Country: GB
    validations:
      required: true
  - type: textarea
    id: data-sources
    attributes:
      label: Valid Blackboard data sources (optional)
      description: >
        This field is not required unless you have insider
        knowledge of the data sources used in your university.

        Read UNIVERSITIES.md for more information.
      placeholder: __00_0
    validations:
      required: false
  - type: textarea
    id: other-details
    attributes:
      label: Anything else to add?
      description: >
        If there is anything else needed to know about
        the login process for your university, you can say so here.
      placeholder: ...
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: License
      description: >
        By submitting this issue, you agree
        that your contribution may be licensed under GPL v2.
      options:
        - label: I agree to follow this project's License
          required: true
